version: "3.3"
services:
    web:
        build:
            context: .
            dockerfile: compose/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./app:/app
            - ./htdocs:/opt/lampp/htdocs
        command: "/store/entrypoint.sh"
